version: "3.7"

services:

  postgres:
    image: postgres:12-alpine
    container_name: postgres-alan
    ports:
      - 5433:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=idiario_development
      - POSTGRES_PASSWORD=postgres

  app:
    image: idiario
    container_name: idiario
    volumes:
      - .:/app
      - box:/box
    environment:
      DB_HOST: postgres-alan
      SECRET_KEY_BASE: d11eeca85a7e981b89b8d2b81d72b8b64b72d159ac231ba320efac45ea6c9d436265b0b8707ce3967942340e95cafaa9523904e070c50b9719b7da000f918817

    ports:
      - 3000:3000

volumes:
  app:
  box:
  pg_data:
